server:
  port: 8012

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: marca-service
          uri: http://localhost:8008
          predicates:
            - Path=/marcas/**
            - Path=/empleado/**
            - Path=/descuento/**
        - id: inasistencia-service
          uri: http://localhost:8009
          predicates:
            - Path=/inasistencias/**
        - id: horaextra-service
          uri: http://localhost:8010
          predicates:
            - Path=/horaextra/**
        - id: sueldo-service
          uri: http://localhost:8011
          predicates:
            - Path=/sueldos/** 