server:
  port: 8012
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true 
      routes:
        - id: marca-service
          uri: lb://marca-service
          predicates:
            - Path=/marcas/**

        - id: inasistencia-service
          uri: lb://inasistencia-service
          predicates:
            - Path=/inasistencias/**

        - id: horaextra-service
          uri: lb://horaextra-service
          predicates:
            - Path=/horaextra/**

        - id: sueldo-service
          uri: lb://sueldo-service
          predicates:
            - Path=/sueldos/**

        - id: sueldo-service
          uri: lb://sueldo-service
          predicates:
            - Path=/descuento/**
            
        - id: sueldo-service
          uri: lb://sueldo-service
          predicates:
            - Path=/empleado/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  #  instance:
  #    hostname: localhost
