server:
  port: 8012

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true 
      routes:
        - id: marca-service
          uri: http://localhost:8008
          predicates:
            - Path=/marcas/**

        - id: inasistencia-service
          uri: http://localhost:8009
          predicates:
            - Path=/inasistencias/**

        - id: horaextra-service
          uri: http://localhost:8010
          predicates:
            - Path=/horaextra/**

        - id: sueldo-service
          uri: http://localhost:8011
          predicates:
            - Path=/sueldos/**

        - id: sueldo-service
          uri: http://localhost:8011
          predicates:
            - Path=/descuento/**
            
        - id: sueldo-service
          uri: http://localhost:8011
          predicates:
            - Path=/empleado/**