spring:
  application:
    name: horaextra-service
# datasource:
#     url: jdbc:mysql://localhost:3306/bdhorasextra
#     username: root
#     password: password
#   jpa:
#     hibernate:
#       ddl-auto: update
server:
  port: 8010
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  # instance:
  #   instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}