spring:
  application:
    name: horaextra-service
server:
  port: 8010
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
  # instance:
  #   instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}